parameters:
    at_core.parser.php_parser.class: AT\CoreBundle\Parser\PHPParser
    at_core.generator.php_generator.class: AT\CoreBundle\Generator\PHPGenerator
    at_core.service.node_service.class: AT\CoreBundle\Service\NodeService

services:
    at_core.parser.php_parser:
        class: %at_core.parser.php_parser.class%
        arguments: []
    at_core.generator.php_generator:
        class: %at_core.generator.php_generator.class%
        arguments: []
    at_core.service.node_service:
        class: %at_core.service.node_service.class%
        arguments:
            - @at_core.repository.operator_repository
            - @at_core.repository.operator_name_repository
            - @at_core.repository.operator_parameter_repository
            - @at_core.repository.operator_parameter_item_repository
            - @at_core.repository.string_repository
            - @at_core.repository.scalar_repository